services:
  app:
    build: .

    container_name: node_app_3

    ports:
      - "3001:3000"

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run dev

    depends_on:
      - mongo

    environment:
      - MONGO_URI=mongodb://mongo:27017/labdb

  mongo:
    image: mongo:8

    container_name: mongo_db

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: